### ISSUE TITLE
Set Node size / color / shape

### ISSUE THREAD

**Issue by alptaciroglu** [paul-shannon/cyjShiny#7]
Hey,

I am trying to shift from old rcytoscapejs to cyjShiny. In the old version, I was able to set node data attributes with the following line:

createCytoscapeJsNetwork(nodeData, edgeData, nodeLabelColor='#000000', edgeTargetShape='none')

nodeData and edgeData objects would have shape and color like attributes that were set with nodeData$shape <- 'rectangle' etc. 

In this new version, I tried to do the same with:

nodeData(g, n, attr='color') <- red ## Example 

When I try this I get;

Error in .verifyAttrName(attr, names(self@defaults)) : 
  unknown attribute name: ‘shape’ 

Error in .verifyAttrName(attr, names(self@defaults)) : 
  unknown attribute name: ‘color’

I get the same errors when I try to set custom edge colors.

I studied the example given in tinyApp.R and I figure ( although unsure ) yeastGalactoseGraphNEL.RData object associating with yeastGalactoseStyle.js file might be responsible from designating the attributes of the nodes. 

In any case, I would appreciate if you could let me know how to set custom node attributes and edge attributes (shapes, size, color) on the same graphNEL object in tinyApp.R example. 

Thanks!!

**Comment by paul-shannon** [comment]
@alptaciroglu  cyjShiny uses the classic Cytoscape approach to control node and edge color, shape and size.  Rather than set them directly you
 - define a visual style which specifies how to render nodes and edges based upon node and edge data attributes
 - set and then change node and edge data attributes at will

The benefit of this approach is that, just once in the style.js file, you specify how you want node and edge ````visual attributes```` to be calculated from node and edge ````data attributes````.  It asks a little more of you to set things up, but subsequent new renderings, reflecting subsequent new data, happens automatically.

You can see this in action in ````cyjShiny/inst/unitTests/cyjShinyDemo.R ````.    New node attributes (node data) is sent to cytoscape.js in the browser with this callback:
````
    observeEvent(input$setNodeAttributes, ignoreInit=TRUE, {
       attribute <- "lfc"
       expression.vector <- switch(input$setNodeAttributes,
                                   "gal1RGexp" = tbl.mrna$gal1RGexp,
                                   "gal4RGexp" = tbl.mrna$gal4RGexp,
                                   "gal80Rexp" = tbl.mrna$gal80Rexp)
       setNodeAttributes(session, attributeName=attribute, nodes=yeastGalactodeNodeIDs, values=expression.vector)
       })
````

If this example is not helpful I can create a minimal example.

**Comment by alptaciroglu** [comment]
Thanks @paul-shannon for quick reply and offer to help !

I will try to figure out myself for a while, let you know if I cannot make something useful. Just to guide myself in the right direction though, I am installing Cytoscape for desktop and going to create a 'style.js' file and export it to load in my shiny app following the same principle you described in tinyApp.R.

**Comment by paul-shannon** [comment]
@alptaciroglu 
cyjShiny development now takes place at https://github.com/cytoscape/cyjShiny - I will archive and make this repo read-only later today.

There is a message for you there:  https://github.com/cytoscape/cyjShiny/issues/17

I made some improvements to tinyApp in hopes of making node size, color, and shape manipulation crystal clear.  Feedback (at cytoscape/cyjShiny) is welcome!
